name: "CI"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  LC_CTYPE: en_US.UTF-8
  LANG: en_US.UTF-8
  RUBY_VERSION: 3.0.1

jobs:
  BuildAndTests:
    name: Build & Tests
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.4.1.app/Contents/Developer
      XCODE_PROJECT: DI.xcodeproj
      IOS_SCHEME: DI iOS
      IOS_DESTINATION: OS=15.5,name=iPhone 13
      IOS_RESULT_PATH: xcodebuild-ios.xcresult
      MACOS_SCHEME: DI macOS
      MACOS_DESTINATION: platform=macOS
      MACOS_RESULT_PATH: xcodebuild-macos.xcresult
      TVOS_SCHEME: DI tvOS
      TVOS_DESTINATION: OS=15.4,name=Apple TV 4K
      TVOS_RESULT_PATH: xcodebuild-tvos.xcresult
      WATCHOS_SCHEME: DI watchOS
      WATCHOS_DESTINATION: OS=8.5,name=Apple Watch Series 7 - 45mm
      WATCHOS_RESULT_PATH: xcodebuild-watchos.xcresult
      SKIP_SWIFTLINT: YES
      DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Bundler
        run: |
          gem install bundler
          bundle install --without=documentation
      - name: Preparation
        run: |
          set -o pipefail
          swift --version
      - name: Test iOS
        run: |
          xcodebuild clean build test \
            -project "$XCODE_PROJECT" \
            -scheme "$IOS_SCHEME" \
            -destination "$IOS_DESTINATION" \
            -resultBundlePath "$IOS_RESULT_PATH" | xcpretty -f `xcpretty-json-formatter`
      - name: Test macOS
        run: |
          xcodebuild clean build test \
            -project "$XCODE_PROJECT" \
            -scheme "$MACOS_SCHEME" \
            -destination "$MACOS_DESTINATION" \
            -resultBundlePath "$MACOS_RESULT_PATH" | xcpretty -f `xcpretty-json-formatter`
      - name: Test tvOS
        run: |
          xcodebuild clean build test \
            -project "$XCODE_PROJECT" \
            -scheme "$TVOS_SCHEME" \
            -destination "$TVOS_DESTINATION" \
            -resultBundlePath "$TVOS_RESULT_PATH" | xcpretty -f `xcpretty-json-formatter`
      - name: Build watchOS
        run: |
          xcodebuild clean build \
            -project "$XCODE_PROJECT" \
            -scheme "$WATCHOS_SCHEME" \
            -destination "$WATCHOS_DESTINATION" \
            -resultBundlePath "$WATCHOS_RESULT_PATH" | xcpretty -f `xcpretty-json-formatter`
      - name: Danger
        run: bundle exec danger --remove-previous-comments

  Cocoapods:
    name: Cocoapods
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Bundler
        run: |
          gem install bundler
          bundle install --without=documentation
      - name: Linting
        run: bundle exec pod lib lint --skip-tests --allow-warnings

  SPM:
    name: Swift Package Manager
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build
